using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace WpfApp2
{
    /// <summary>
    /// Interaction logic for FinalWindow.xaml
    /// </summary>
    public partial class FinalWindow : Window
    {
        public FinalWindow(Machinery.Rows alpha, Machinery.Rows omega)
        {
            InitializeComponent();

            int[][] OG_Matrix = alpha.getmatrix();
            int[][] new_Matrix = omega.getmatrix();

            R11_OG.Text = OG_Matrix[0][0].ToString();
            R12_OG.Text = OG_Matrix[0][1].ToString();
            R13_OG.Text = OG_Matrix[0][2].ToString();
            R14_OG.Text = OG_Matrix[0][3].ToString();
            R15_OG.Text = OG_Matrix[0][4].ToString();
            R16_OG.Text = OG_Matrix[0][5].ToString();
            R17_OG.Text = OG_Matrix[0][6].ToString();
            R18_OG.Text = OG_Matrix[0][7].ToString();
            R19_OG.Text = OG_Matrix[0][8].ToString();
            R21_OG.Text = OG_Matrix[1][0].ToString();
            R22_OG.Text = OG_Matrix[1][1].ToString();
            R23_OG.Text = OG_Matrix[1][2].ToString();
            R24_OG.Text = OG_Matrix[1][3].ToString();
            R25_OG.Text = OG_Matrix[1][4].ToString();
            R26_OG.Text = OG_Matrix[1][5].ToString();
            R27_OG.Text = OG_Matrix[1][6].ToString();
            R28_OG.Text = OG_Matrix[1][7].ToString();
            R29_OG.Text = OG_Matrix[1][8].ToString();
            R31_OG.Text = OG_Matrix[2][0].ToString();
            R32_OG.Text = OG_Matrix[2][1].ToString();
            R33_OG.Text = OG_Matrix[2][2].ToString();
            R34_OG.Text = OG_Matrix[2][3].ToString();
            R35_OG.Text = OG_Matrix[2][4].ToString();
            R36_OG.Text = OG_Matrix[2][5].ToString();
            R37_OG.Text = OG_Matrix[2][6].ToString();
            R38_OG.Text = OG_Matrix[2][7].ToString();
            R39_OG.Text = OG_Matrix[2][8].ToString();
            R41_OG.Text = OG_Matrix[3][0].ToString();
            R42_OG.Text = OG_Matrix[3][1].ToString();
            R43_OG.Text = OG_Matrix[3][2].ToString();
            R44_OG.Text = OG_Matrix[3][3].ToString();
            R45_OG.Text = OG_Matrix[3][4].ToString();
            R46_OG.Text = OG_Matrix[3][5].ToString();
            R47_OG.Text = OG_Matrix[3][6].ToString();
            R48_OG.Text = OG_Matrix[3][7].ToString();
            R49_OG.Text = OG_Matrix[3][8].ToString();
            R51_OG.Text = OG_Matrix[4][0].ToString();
            R52_OG.Text = OG_Matrix[4][1].ToString();
            R53_OG.Text = OG_Matrix[4][2].ToString();
            R54_OG.Text = OG_Matrix[4][3].ToString();
            R55_OG.Text = OG_Matrix[4][4].ToString();
            R56_OG.Text = OG_Matrix[4][5].ToString();
            R57_OG.Text = OG_Matrix[4][6].ToString();
            R58_OG.Text = OG_Matrix[4][7].ToString();
            R59_OG.Text = OG_Matrix[4][8].ToString();
            R61_OG.Text = OG_Matrix[5][0].ToString();
            R62_OG.Text = OG_Matrix[5][1].ToString();
            R63_OG.Text = OG_Matrix[5][2].ToString();
            R64_OG.Text = OG_Matrix[5][3].ToString();
            R65_OG.Text = OG_Matrix[5][4].ToString();
            R66_OG.Text = OG_Matrix[5][5].ToString();
            R67_OG.Text = OG_Matrix[5][6].ToString();
            R68_OG.Text = OG_Matrix[5][7].ToString();
            R69_OG.Text = OG_Matrix[5][8].ToString();
            R71_OG.Text = OG_Matrix[6][0].ToString();
            R72_OG.Text = OG_Matrix[6][1].ToString();
            R73_OG.Text = OG_Matrix[6][2].ToString();
            R74_OG.Text = OG_Matrix[6][3].ToString();
            R75_OG.Text = OG_Matrix[6][4].ToString();
            R76_OG.Text = OG_Matrix[6][5].ToString();
            R77_OG.Text = OG_Matrix[6][6].ToString();
            R78_OG.Text = OG_Matrix[6][7].ToString();
            R79_OG.Text = OG_Matrix[6][8].ToString();
            R81_OG.Text = OG_Matrix[7][0].ToString();
            R82_OG.Text = OG_Matrix[7][1].ToString();
            R83_OG.Text = OG_Matrix[7][2].ToString();
            R84_OG.Text = OG_Matrix[7][3].ToString();
            R85_OG.Text = OG_Matrix[7][4].ToString();
            R86_OG.Text = OG_Matrix[7][5].ToString();
            R87_OG.Text = OG_Matrix[7][6].ToString();
            R88_OG.Text = OG_Matrix[7][7].ToString();
            R89_OG.Text = OG_Matrix[7][8].ToString();
            R91_OG.Text = OG_Matrix[8][0].ToString();
            R92_OG.Text = OG_Matrix[8][1].ToString();
            R93_OG.Text = OG_Matrix[8][2].ToString();
            R94_OG.Text = OG_Matrix[8][3].ToString();
            R95_OG.Text = OG_Matrix[8][4].ToString();
            R96_OG.Text = OG_Matrix[8][5].ToString();
            R97_OG.Text = OG_Matrix[8][6].ToString();
            R98_OG.Text = OG_Matrix[8][7].ToString();
            R99_OG.Text = OG_Matrix[8][8].ToString();

            R11.Text = new_Matrix[0][0].ToString();
            R12.Text = new_Matrix[0][1].ToString();
            R13.Text = new_Matrix[0][2].ToString();
            R14.Text = new_Matrix[0][3].ToString();
            R15.Text = new_Matrix[0][4].ToString();
            R16.Text = new_Matrix[0][5].ToString();
            R17.Text = new_Matrix[0][6].ToString();
            R18.Text = new_Matrix[0][7].ToString();
            R19.Text = new_Matrix[0][8].ToString();
            R21.Text = new_Matrix[1][0].ToString();
            R22.Text = new_Matrix[1][1].ToString();
            R23.Text = new_Matrix[1][2].ToString();
            R24.Text = new_Matrix[1][3].ToString();
            R25.Text = new_Matrix[1][4].ToString();
            R26.Text = new_Matrix[1][5].ToString();
            R27.Text = new_Matrix[1][6].ToString();
            R28.Text = new_Matrix[1][7].ToString();
            R29.Text = new_Matrix[1][8].ToString();
            R31.Text = new_Matrix[2][0].ToString();
            R32.Text = new_Matrix[2][1].ToString();
            R33.Text = new_Matrix[2][2].ToString();
            R34.Text = new_Matrix[2][3].ToString();
            R35.Text = new_Matrix[2][4].ToString();
            R36.Text = new_Matrix[2][5].ToString();
            R37.Text = new_Matrix[2][6].ToString();
            R38.Text = new_Matrix[2][7].ToString();
            R39.Text = new_Matrix[2][8].ToString();
            R41.Text = new_Matrix[3][0].ToString();
            R42.Text = new_Matrix[3][1].ToString();
            R43.Text = new_Matrix[3][2].ToString();
            R44.Text = new_Matrix[3][3].ToString();
            R45.Text = new_Matrix[3][4].ToString();
            R46.Text = new_Matrix[3][5].ToString();
            R47.Text = new_Matrix[3][6].ToString();
            R48.Text = new_Matrix[3][7].ToString();
            R49.Text = new_Matrix[3][8].ToString();
            R51.Text = new_Matrix[4][0].ToString();
            R52.Text = new_Matrix[4][1].ToString();
            R53.Text = new_Matrix[4][2].ToString();
            R54.Text = new_Matrix[4][3].ToString();
            R55.Text = new_Matrix[4][4].ToString();
            R56.Text = new_Matrix[4][5].ToString();
            R57.Text = new_Matrix[4][6].ToString();
            R58.Text = new_Matrix[4][7].ToString();
            R59.Text = new_Matrix[4][8].ToString();
            R61.Text = new_Matrix[5][0].ToString();
            R62.Text = new_Matrix[5][1].ToString();
            R63.Text = new_Matrix[5][2].ToString();
            R64.Text = new_Matrix[5][3].ToString();
            R65.Text = new_Matrix[5][4].ToString();
            R66.Text = new_Matrix[5][5].ToString();
            R67.Text = new_Matrix[5][6].ToString();
            R68.Text = new_Matrix[5][7].ToString();
            R69.Text = new_Matrix[5][8].ToString();
            R71.Text = new_Matrix[6][0].ToString();
            R72.Text = new_Matrix[6][1].ToString();
            R73.Text = new_Matrix[6][2].ToString();
            R74.Text = new_Matrix[6][3].ToString();
            R75.Text = new_Matrix[6][4].ToString();
            R76.Text = new_Matrix[6][5].ToString();
            R77.Text = new_Matrix[6][6].ToString();
            R78.Text = new_Matrix[6][7].ToString();
            R79.Text = new_Matrix[6][8].ToString();
            R81.Text = new_Matrix[7][0].ToString();
            R82.Text = new_Matrix[7][1].ToString();
            R83.Text = new_Matrix[7][2].ToString();
            R84.Text = new_Matrix[7][3].ToString();
            R85.Text = new_Matrix[7][4].ToString();
            R86.Text = new_Matrix[7][5].ToString();
            R87.Text = new_Matrix[7][6].ToString();
            R88.Text = new_Matrix[7][7].ToString();
            R89.Text = new_Matrix[7][8].ToString();
            R91.Text = new_Matrix[8][0].ToString();
            R92.Text = new_Matrix[8][1].ToString();
            R93.Text = new_Matrix[8][2].ToString();
            R94.Text = new_Matrix[8][3].ToString();
            R95.Text = new_Matrix[8][4].ToString();
            R96.Text = new_Matrix[8][5].ToString();
            R97.Text = new_Matrix[8][6].ToString();
            R98.Text = new_Matrix[8][7].ToString();
            R99.Text = new_Matrix[8][8].ToString();
        }
    }
}
